name: JustPay Linux Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            libcurl4-openssl-dev \
            libsqlite3-dev \
            libgl1-mesa-dev \
            libxkbcommon-x11-0

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.2
          host: linux
          target: desktop
          arch: gcc_64
          modules: qtquickcontrols2 qtsvg

      - name: Configure (Release)
        run: |
          cmake -S . -B build -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --parallel 4

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: JustPay-linux
          path: build/JustPay
