name: JustPay Linux Build

on:
  push:
    branches: [main]
    tags:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clean Qt cache
        run: |
          rm -rf ~/.cache/aqtinstall || true
          rm -rf ~/Qt || true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            ninja-build \
            libcurl4-openssl-dev \
            libsqlite3-dev \
            libgl1-mesa-dev \
            libxkbcommon-x11-0

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7.2
          host: linux
          target: desktop
          arch: "linux_gcc_64"
          aqtversion: "==3.1.7"

      - name: Configure (Release)
        run: |
          cmake -S . -B build/release -G Ninja \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build/release --parallel 4

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/release/JustPay
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
